version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shisecal-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - shisecal-network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - REDIS_HOST=redis

  nginx:
    image: nginx:alpine
    container_name: shisecal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - shisecal-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: shisecal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shisecal_production
      MYSQL_USER: shisecal_user
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shisecal-network

  redis:
    image: redis:7-alpine
    container_name: shisecal-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass your_redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - shisecal-network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  shisecal-network:
    driver: bridge