name: 'Deployment Logger'
description: 'Log deployment activities and metrics'
inputs:
  log-level:
    description: 'Log level (info, warn, error)'
    required: false
    default: 'info'
  message:
    description: 'Log message'
    required: true
  deployment-id:
    description: 'Deployment ID for tracking'
    required: false
outputs:
  log-file:
    description: 'Path to the generated log file'
runs:
  using: 'composite'
  steps:
    - name: Create log entry
      shell: bash
      run: |
        echo "[${{ inputs.log-level }}] $(date): ${{ inputs.message }}" >> deployment.log
        echo "log-file=deployment.log" >> $GITHUB_OUTPUT
    
    - name: Upload log artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: deployment-logs-${{ github.run_id }}
        path: deployment.log
        retention-days: 30