name: Deploy to AWS

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/shicecal
          git pull origin production
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          php artisan migrate --force
          php artisan db:seed --class=AdminUserSeeder --force
          php artisan db:seed --class=FacilitySeeder --force
          php artisan db:seed --class=LandInfoSeeder --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart nginx
          sudo systemctl restart php-fpm