<?php

return [
    'facility' => [
        'title' => '基本情報',
        'icon' => 'fas fa-building',
        'color' => 'text-primary',
        'fields' => [
            'company_name' => '会社名',
            'office_code' => '事業所コード',
            'facility_name' => '施設名',
            'designation_number' => '指定番号1',
            'designation_number_2' => '指定番号2',
            'postal_code' => '郵便番号',
            'opening_date' => '開設日',
            'address' => '住所',
            'opening_years' => '開設年数',
            'building_name' => '住所（建物名）',
            'building_structure' => '建物構造',
            'phone_number' => '電話番号',
            'building_floors' => '建物階数',
            'fax_number' => 'FAX番号',
            'paid_rooms_count' => '居室数',
            'toll_free_number' => 'フリーダイヤル',
            'ss_rooms_count' => '内SS数',
            'email' => 'メールアドレス',
            'capacity' => '定員数',
            'website_url' => 'URL',
            'service_types' => 'サービス種類',
            'service_validity_periods' => 'サービス有効期限',
        ]
    ],
    'land' => [
        'title' => '土地情報',
        'icon' => 'fas fa-map-marked-alt',
        'color' => 'text-success',
        'fields' => [
            'land_ownership_type' => '土地所有区分',
            'land_site_area_sqm' => '敷地面積（㎡数）',
            'land_site_area_tsubo' => '敷地面積（坪数）',
            'land_parking_spaces' => '敷地内駐車場台数',
            'land_purchase_price' => '購入金額',
            'land_unit_price_per_tsubo' => '坪単価',
            'land_monthly_rent' => '家賃',
            'land_contract_period' => '契約期間',
            'land_auto_renewal' => '自動更新の有無',
            'land_contract_period_text' => '契約年数',
            'land_notes' => '土地備考',
            'land_management_company_name' => '土地管理会社名',
            'land_management_company_postal_code' => '土地管理会社郵便番号',
            'land_management_company_address' => '土地管理会社住所',
            'land_management_company_building' => '土地管理会社住所（建物名）',
            'land_management_company_phone' => '土地管理会社電話番号',
            'land_management_company_fax' => '土地管理会社FAX番号',
            'land_management_company_email' => '土地管理会社メールアドレス',
            'land_management_company_url' => '土地管理会社URL',
            'land_management_company_notes' => '土地管理会社備考',
            'land_owner_name' => '土地オーナー氏名',
            'land_owner_postal_code' => '土地オーナー郵便番号',
            'land_owner_address' => '土地オーナー住所',
            'land_owner_building' => '土地オーナー住所（建物名）',
            'land_owner_phone' => '土地オーナー電話番号',
            'land_owner_fax' => '土地オーナーFAX番号',
            'land_owner_email' => '土地オーナーメールアドレス',
            'land_owner_url' => '土地オーナーURL',
            'land_owner_notes' => '土地オーナー備考',
        ]
    ],
    'lifeline_electrical' => [
        'title' => '電気設備',
        'icon' => 'fas fa-bolt',
        'color' => 'text-warning',
        'fields' => [
            'electrical_contractor' => '電力会社',
            'electrical_safety_management_company' => '電気保安管理業者',
            'electrical_maintenance_inspection_date' => '電気保守点検実施日',
            'electrical_pas_availability' => 'PAS有無',
            'electrical_pas_update_date' => 'PAS更新年月日',
            'electrical_cubicle_availability' => 'キュービクル有無',
            'electrical_cubicle_manufacturers' => 'キュービクルメーカー',
            'electrical_cubicle_model_years' => 'キュービクル年式',
            'electrical_generator_availability' => '非常用発電機有無',
            'electrical_generator_manufacturers' => '非常用発電機メーカー',
            'electrical_generator_model_years' => '非常用発電機年式',
            'electrical_notes' => '電気設備備考',
        ]
    ],
    'lifeline_water' => [
        'title' => '水道設備',
        'icon' => 'fas fa-tint',
        'color' => 'text-info',
        'fields' => [
            'water_contractor' => '水道契約会社',
            'water_tank_cleaning_company' => '受水槽清掃業者',
            'water_tank_cleaning_date' => '受水槽清掃実施日',
            'water_filter_bath_system' => '浴槽循環方式',
            'water_filter_availability' => 'ろ過器設置の有無',
            'water_filter_manufacturer' => 'ろ過器メーカー',
            'water_filter_model_year' => 'ろ過器年式',
            'water_tank_availability' => '受水槽設置の有無',
            'water_tank_manufacturer' => '受水槽メーカー',
            'water_tank_model_year' => '受水槽年式',
            'water_pump_manufacturers' => '加圧ポンプメーカー',
            'water_pump_model_years' => '加圧ポンプ年式',
            'water_septic_tank_availability' => '浄化槽設置の有無',
            'water_septic_tank_manufacturer' => '浄化槽メーカー',
            'water_septic_tank_model_year' => '浄化槽年式',
            'water_septic_tank_inspection_company' => '浄化槽点検・清掃業者',
            'water_septic_tank_inspection_date' => '浄化槽点検・清掃実施日',
            'water_legionella_inspection_dates' => 'レジオネラ検査実施日',
            'water_legionella_first_results' => 'レジオネラ検査結果（初回）',
            'water_legionella_second_results' => 'レジオネラ検査結果（2回目）',
            'water_notes' => '水道設備備考',
        ]
    ],
    'building' => [
        'title' => '建物情報',
        'icon' => 'fas fa-building',
        'color' => 'text-info',
        'fields' => [
            'building_ownership_type' => '建物所有区分',
            'building_area_sqm' => '建築面積（㎡数）',
            'building_area_tsubo' => '建築面積（坪数）',
            'building_completion_date' => '竣工日',
            'building_total_floor_area_sqm' => '延床面積（㎡数）',
            'building_total_floor_area_tsubo' => '延べ床面積（坪数）',
            'building_age' => '築年数',
            'building_construction_cost' => '建築費用',
            'building_cost_per_tsubo' => '坪単価',
            'building_useful_life' => '耐用年数',
            'building_construction_cooperation_fee' => '建設協力金',
            'building_monthly_rent' => '建物家賃',
            'building_contract_years' => '建物契約年数',
            'building_contract_start_date' => '建物契約開始日',
            'building_contract_end_date' => '建物契約終了日',
            'building_auto_renewal' => '建物自動更新の有無',
            'building_construction_company_name' => '施工会社',
            'building_construction_company_phone' => '施工会社連絡先',
            'building_periodic_inspection_type' => '定期調査会社',
            'building_periodic_inspection_date' => '調査日',
            'building_notes' => '建物備考',
            'building_management_company_name' => '建物管理会社名',
            'building_management_company_phone' => '建物管理会社電話番号',
            'building_management_company_email' => '建物管理会社メールアドレス',
            'building_owner_name' => '建物オーナー氏名',
            'building_owner_phone' => '建物オーナー電話番号',
            'building_owner_email' => '建物オーナーメールアドレス',
        ]
    ],
    'lifeline_gas' => [
        'title' => 'ガス設備',
        'icon' => 'fas fa-fire',
        'color' => 'text-danger',
        'fields' => [
            'gas_contractor' => 'ガス会社',
            'gas_safety_management_company' => 'ガス保安管理業者',
            'gas_maintenance_inspection_date' => 'ガス保守点検実施日',
            'gas_notes' => 'ガス設備備考',
        ]
    ],
    'lifeline_elevator' => [
        'title' => 'エレベーター設備',
        'icon' => 'fas fa-elevator',
        'color' => 'text-secondary',
        'fields' => [
            'elevator_availability' => 'エレベーター有無',
            'elevator_manufacturer' => 'エレベーターメーカー',
            'elevator_model_year' => 'エレベーター年式',
            'elevator_maintenance_company' => 'エレベーター保守会社',
            'elevator_maintenance_date' => 'エレベーター保守実施日',
            'elevator_notes' => 'エレベーター設備備考',
        ]
    ],
    'lifeline_hvac' => [
        'title' => '空調・照明設備',
        'icon' => 'fas fa-snowflake',
        'color' => 'text-success',
        'fields' => [
            'hvac_lighting_availability' => '空調・照明設備有無',
            'hvac_lighting_manufacturer' => '空調・照明設備メーカー',
            'hvac_lighting_model_year' => '空調・照明設備年式',
            'hvac_lighting_maintenance_company' => '空調・照明保守会社',
            'hvac_lighting_maintenance_date' => '空調・照明保守実施日',
            'hvac_lighting_notes' => '空調・照明設備備考',
        ]
    ],
];