name: 'Slack Notification'
description: 'Send notifications to Slack'
inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
  status:
    description: 'Status (success, failure, warning)'
    required: false
    default: 'info'
runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      shell: bash
      run: |
        if [ -n "${{ inputs.webhook-url }}" ]; then
          STATUS_EMOJI=""
          case "${{ inputs.status }}" in
            "success") STATUS_EMOJI="✅" ;;
            "failure") STATUS_EMOJI="❌" ;;
            "warning") STATUS_EMOJI="⚠️" ;;
            *) STATUS_EMOJI="ℹ️" ;;
          esac
          
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS_EMOJI ${{ inputs.message }}\"}" \
            "${{ inputs.webhook-url }}"
        else
          echo "Slack webhook URL not provided, skipping notification"
        fi