name: Deploy to AWS

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/shicecal
          git pull origin production
          composer install --no-dev --optimize-autoloader
          npm ci --production=false
          
          # Clear existing build artifacts
          rm -rf public/build
          
          # Build assets with Vite
          npm run build
          
          # Verify build output
          if [ ! -d "public/build" ]; then
            echo "❌ Asset build failed"
            exit 1
          fi
          
          if [ ! -f "public/build/manifest.json" ]; then
            echo "❌ Vite manifest file not generated"
            exit 1
          fi
          
          echo "✅ Asset build completed - Files: $(find public/build -type f | wc -l)"
          
          php artisan migrate --force
          php artisan db:seed --class=AdminUserSeeder --force
          php artisan db:seed --class=FacilitySeeder --force
          php artisan db:seed --class=LandInfoSeeder --force
          
          # Clear existing caches first
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear
          
          # Rebuild optimized caches
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Verify Vite manifest exists and is valid
          if [ ! -f "public/build/manifest.json" ]; then
            echo "❌ Vite manifest file missing after cache rebuild"
            exit 1
          fi
          
          # Validate manifest JSON
          if ! php -r "json_decode(file_get_contents('public/build/manifest.json')); if (json_last_error() !== JSON_ERROR_NONE) exit(1);"; then
            echo "❌ Vite manifest file is invalid"
            exit 1
          fi
          
          echo "✅ Deployment verification completed"
          
          sudo systemctl restart nginx
          sudo systemctl restart php-fpm