name: Minimal Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  minimal-check:
    name: Minimal Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check PHP version
      run: php --version
      
    - name: Check Node version
      run: node --version
      
    - name: Check Composer
      run: composer --version
      
    - name: Check npm
      run: npm --version
      
    - name: List files
      run: ls -la
      
    - name: Check package.json
      run: cat package.json | head -20
      
    - name: Check composer.json
      run: cat composer.json | head -20
      
    - name: Success
      run: echo "✅ Minimal test completed successfully"